export const SITE_EMAIL = "kevin@ziwuxx.com";

export const STATS = {
  zh: [
    ["100+", "海内外高校协作关系"],
    ["3,000+", "基础 AI 数据人才"],
    ["2,000+", "优质本科人才"],
    ["1,000+", "硕博与专业人才"],
  ],
  en: [
    ["100+", "University relationships"],
    ["3,000+", "AI data contributors"],
    ["2,000+", "Strong undergraduates"],
    ["1,000+", "Graduate & specialist talent"],
  ],
};

const servicesZh = [
  {
    id: "01",
    title: "专家数据与 Golden Set",
    label: "Expert data",
    body: "围绕真实专业任务构建指令、参考答案、长上下文、评分量规与可复用金标集。",
    items: ["专家作答与参考输出", "复杂推理与长上下文", "事实核验与领域质检"],
  },
  {
    id: "02",
    title: "模型后训练与偏好数据",
    label: "Post-training",
    body: "将人类判断转化为偏好排序、批评、改写与可解释打分，支持训练后的模型迭代。",
    items: ["偏好比较与排序", "量规打分与错误分析", "安全与边界审阅"],
  },
  {
    id: "03",
    title: "Agent 与复杂任务评测",
    label: "Agent evals",
    body: "不仅看最终答案，也审阅任务设定、工具使用、执行轨迹、交付物与评测可靠性。",
    items: ["任务有效性", "过程与轨迹审阅", "失败归因与评委校准"],
  },
  {
    id: "04",
    title: "多模态与具身数据",
    label: "Multimodal",
    body: "组织视觉、语音、二维/三维融合、视频语义与具身智能动作数据的规模化生产。",
    items: ["图像 / 视频 / OCR", "语音与方言数据", "点云与动作语义"],
  },
  {
    id: "05",
    title: "合成数据验证",
    label: "Synthetic QA",
    body: "对机器生成内容进行专业筛选、去重、纠错、难度分层与人类确认，让合成数据可用于训练。",
    items: ["生成结果筛选", "覆盖度与难度校准", "人类确认与金标抽检"],
  },
  {
    id: "06",
    title: "托管式生产与质检",
    label: "Managed delivery",
    body: "从试标、培训、排产到 QA、返修与验收，由同一交付团队承担，不把管理成本转回客户。",
    items: ["项目制资格筛选", "分层生产与进度管理", "证据化质检与返修"],
  },
];

const servicesEn = [
  {
    id: "01",
    title: "Expert data & golden sets",
    label: "Expert data",
    body: "Domain prompts, reference outputs, long-context tasks, rubrics and reusable gold sets built around real professional work.",
    items: ["Expert-authored outputs", "Complex reasoning & context", "Fact validation & domain QA"],
  },
  {
    id: "02",
    title: "Post-training & preference data",
    label: "Post-training",
    body: "Human judgment captured as rankings, critiques, rewrites and explainable scores for model iteration after pre-training.",
    items: ["Preference comparison", "Rubric scoring & error analysis", "Safety and boundary review"],
  },
  {
    id: "03",
    title: "Agent & complex-task evaluation",
    label: "Agent evals",
    body: "Evaluation across task validity, tool use, execution trajectories, final deliverables and judge reliability—not only the answer.",
    items: ["Task validity", "Trajectory review", "Failure attribution & judge calibration"],
  },
  {
    id: "04",
    title: "Multimodal & embodied data",
    label: "Multimodal",
    body: "Managed production for vision, speech, 2D/3D fusion, video semantics and embodied-action datasets.",
    items: ["Image / video / OCR", "Speech & dialect data", "Point cloud & action semantics"],
  },
  {
    id: "05",
    title: "Synthetic-data validation",
    label: "Synthetic QA",
    body: "Expert filtering, de-duplication, correction, difficulty calibration and human confirmation for machine-generated data.",
    items: ["Generation screening", "Coverage & difficulty calibration", "Human confirmation & gold sampling"],
  },
  {
    id: "06",
    title: "Managed production & QA",
    label: "Managed delivery",
    body: "One delivery team owns trials, qualification, training, production, QA, rework and acceptance—without shifting workforce management back to the client.",
    items: ["Project-specific qualification", "Tiered production management", "Evidence-based QA & rework"],
  },
];

export const SERVICES = { zh: servicesZh, en: servicesEn };

export const CASES = [
  {
    slug: "financial-compliance",
    image: "/meridian/v4/zh/finance.jpg",
    imageEn: "/meridian/v4/en/finance.jpg",
    tone: "teal",
    metrics: [["300+", "team"], ["100K+", "monthly"], ["99.8%", "accuracy"]],
    zh: {
      tag: "金融 · 合规",
      title: "金融进件安全审核与文本标注",
      summary: "面向规则密集金融流程的领域文档审阅、风险识别与专业质检。",
      body: "专业金融团队按合规与风控规则审阅进件材料，完成结构化标注与风险点识别。人员经过金融背景、产品知识、进件规范与保密要求筛选，运营质检与领域复核并行。",
      deliveryModel: "金融背景筛选 × 运营质检 × 领域复核",
      proof: ["金融专业背景筛选", "规则化风险点识别", "百人级稳定生产"],
    },
    en: {
      tag: "Finance · Compliance",
      title: "Financial compliance & text review",
      summary: "Domain-aligned document review, risk identification and specialist QA for rule-heavy finance workflows.",
      body: "A finance-qualified team reviewed intake materials against compliance and risk-control rules, producing structured labels and risk findings. Qualification covered domain background, product knowledge, operating norms and confidentiality.",
      deliveryModel: "Finance qualification × operations QA × domain review",
      proof: ["Finance-qualified contributors", "Rule-based risk identification", "Stable hundred-person production"],
    },
  },
  {
    slug: "multimodal-annotation",
    image: "/meridian/v4/zh/lidar.jpg",
    imageEn: "/meridian/v4/en/lidar.jpg",
    tone: "gold",
    metrics: [["150+", "team"], ["500K", "frames"], ["98%", "accuracy"]],
    zh: {
      tag: "自动驾驶",
      title: "2D / 3D 融合联合标注",
      summary: "同步图像二维框与点云三维框，统一类别、遮挡、方向与属性。",
      body: "项目建立像素平面与空间坐标的统一映射，由全职现场团队完成生产，并通过多模态质检控制漏标、错配与朝向问题。",
      deliveryModel: "全职现场生产 × 二维 / 三维协同质检",
      proof: ["二维与三维协同", "全职现场产线", "规模化多模态 QA"],
    },
    en: {
      tag: "Autonomous driving",
      title: "2D / 3D multimodal annotation",
      summary: "Coordinated image and point-cloud labeling across class, occlusion, heading and attributes.",
      body: "The workflow aligned pixel-space objects with spatial cuboids. A full-time production team handled delivery while multimodal QA checked omissions, mismatches and heading accuracy.",
      deliveryModel: "Full-time production × coordinated 2D / 3D QA",
      proof: ["2D/3D coordination", "Full-time production benches", "Multimodal QA at scale"],
    },
  },
  {
    slug: "speech-asr",
    image: "/photos/seminar.jpg",
    imageEn: "/photos/seminar.jpg",
    tone: "red",
    metrics: [["400+", "people"], ["20K", "hours"], ["95%+", "acceptance"]],
    zh: {
      tag: "语音",
      title: "多地方言音视频采标",
      summary: "覆盖多区域方言的采集、转写、结构化标注与数据集级验收。",
      body: "方言母语者按脚本完成标准化采集；标注与质检团队完成转写、音素类结构化处理与全链路 QA。验收落到数据集，而不止单条片段。",
      deliveryModel: "区域母语者组织 × 采集转写 × 数据集验收",
      proof: ["区域级母语者组织", "采集与转写一体", "数据集级验收"],
    },
    en: {
      tag: "Speech",
      title: "Multi-dialect speech / ASR data",
      summary: "Regional collection, transcription, structured annotation and dataset-level acceptance.",
      body: "Native speakers recorded standardized audio from scripts. Annotation and QA teams delivered transcription, structured phonetic work and full-chain checks, with acceptance measured at dataset level.",
      deliveryModel: "Regional sourcing × capture and transcription × dataset QA",
      proof: ["Regional native-speaker supply", "Integrated capture & transcription", "Dataset-level acceptance"],
    },
  },
  {
    slug: "agent-evaluation",
    image: "/meridian/v4/zh/agent.jpg",
    imageEn: "/meridian/v4/en/agent.jpg",
    tone: "blue",
    metrics: [["4", "stages"], ["A/B", "independent"], ["C", "adjudication"]],
    zh: {
      tag: "高阶评测",
      title: "复杂任务与 Agent 评测",
      summary: "从输入质量、执行轨迹、交付物到评委可靠性，完整审阅复杂 AI 工作。",
      body: "专业领域评测员检查任务是否可执行、模型如何规划和使用工具、交付物是否可用，以及原始评分是否可信。两路独立审阅经质检裁决合并，人类判断保留最终权威。",
      deliveryModel: "独立双评 × 轨迹审阅 × 质检裁决",
      proof: ["输入—过程—输出—评委四层", "独立双评与质检裁决", "有证据的失败归因"],
    },
    en: {
      tag: "Advanced evaluation",
      title: "Complex-task & agent evaluation",
      summary: "Full-stack review from input validity and execution trajectory to deliverable quality and judge reliability.",
      body: "Domain evaluators checked task executability, planning and tool use, deliverable usability and scoring reliability. Two independent reviews were merged through a QA adjudication layer, with human judgment as final authority.",
      deliveryModel: "Independent review × trajectory analysis × QA adjudication",
      proof: ["Input–process–output–judge stack", "Independent review & adjudication", "Evidence-grounded failure attribution"],
    },
  },
  {
    slug: "embodied-ai",
    image: "/work/embodied-action-v6.png",
    imageEn: "/work/embodied-action-v6.png",
    tone: "violet",
    metrics: [["100+", "team"], ["3,000", "hours"], ["5", "QA dimensions"]],
    zh: {
      tag: "具身智能",
      title: "具身智能动作语义数据",
      summary: "面向机械臂与第一人称操作视频，完成片段切分、动作 / 物体语义、指令配对与边界质检。",
      body: "团队先理解整段操作目标，再审阅片段边界、动作重叠和关键状态变化；随后校正动作、物体、位置、属性、方向与视角，并把指令绑定到可见行为证据。",
      deliveryModel: "视频级理解 × 五维语义校正 × 边界质检",
      proof: ["视频级任务理解", "动作与物体语义校正", "指令绑定可见证据"],
    },
    en: {
      tag: "Embodied AI",
      title: "Embodied-action semantic data",
      summary: "Segmentation, action/object semantics, instruction pairing and boundary QA for robotic and first-person manipulation video.",
      body: "Teams first established the full manipulation goal, then reviewed segment boundaries, overlapping actions and key state changes. Action, object, location, attributes, direction and viewpoint were corrected before instructions were tied to visible evidence.",
      deliveryModel: "Video-level review × semantic QA × boundary checks",
      proof: ["Video-level task understanding", "Action and object semantic QA", "Instructions tied to visible evidence"],
    },
  },
  {
    slug: "finance-long-context",
    image: "/photos/documents.jpg",
    tone: "gold",
    metrics: [["3–10", "turns"], ["≤64K", "context"], ["9", "dimensions"]],
    zh: {
      tag: "专家数据 · 金融",
      title: "金融长上下文专家数据",
      summary: "围绕研究、估值、风控、合规与银行业务构建多源沙箱和逐轮量规。",
      body: "专家从多份专业来源抽取材料，组成有边界的长上下文，提出贴近真实工作的任务，并对模型答案进行逐轮打分、对比与排序。",
      deliveryModel: "专家沙箱 × 多源上下文 × 逐轮量规",
      proof: ["多源长上下文", "真实专业任务", "逐轮量规与 A/B 评测"],
    },
    en: {
      tag: "Expert data · Finance",
      title: "Financial long-context expert data",
      summary: "Multi-source sandboxes and turn-level rubrics for research, valuation, risk, compliance and banking tasks.",
      body: "Experts assembled bounded context from professional sources, authored tasks reflecting real work, then scored and ranked model answers turn by turn.",
      deliveryModel: "Expert sandbox × multi-source context × turn-level rubrics",
      proof: ["Multi-source long context", "Authentic professional tasks", "Turn-level rubrics & A/B evaluation"],
    },
  },
];

export const COPY = {
  zh: {
    lang: "zh",
    brand: "子午象限",
    brandSub: "AXISX",
    nav: [
      ["能力", "/services"],
      ["交付", "/delivery"],
      ["案例", "/work"],
      ["子午台", "/meridian"],
      ["质量", "/quality"],
      ["未来", "/future"],
      ["公司", "/about"],
    ],
    contact: "邮件联系",
    language: "EN",
    home: {
      eyebrow: "MANAGED HUMAN COMPUTE · CHINA DELIVERY",
      title: "把专业知识\n变成模型可用的数据",
      lead: "子午象限把高校人才、领域专家与全流程质检组织成托管式交付网络，为模型后训练、Golden Set、Agent 评测与多模态作业提供从试标到验收的一体化能力。",
      primary: "提交项目简报",
      secondary: "查看交付案例",
      proof: "不是出售人头。我们交付经过筛选、生产、质检和验收的结果。",
      stackTitle: "交付系统",
      stack: ["任务设计与校准", "人才分层与资格筛选", "生产、QA 与返修", "达标批次与反馈闭环"],
      servicesTitle: "从数据生产到评测闭环",
      servicesLead: "围绕模型真正缺少的专业判断，组合专家、流程与质量控制。",
      casesTitle: "代表交付",
      casesLead: "既能组织高难度专家工作，也能稳定承接规模化多模态生产。",
      processTitle: "把不确定的人力，变成可管理的交付",
      processLead: "客户校准标准，我们负责把标准转化为人员、作业与质量系统。",
      platformTitle: "子午台：交付背后的作业层",
      platformBody: "正在建设中的内部作业基础设施，围绕任务分发、生产、抽检、返修和批次追踪逐步上线。页面展示的是当前产品原型与真实交付场景的结合，不作为独立 SaaS 对外销售。",
    },
    common: {
      allCases: "查看全部案例",
      learnMore: "了解详情",
      contactTitle: "先发一个真实任务",
      contactBody: "提供 SOP、样本、体量与验收标准，我们将在 24 小时内返回初步可行性判断。",
      email: "直接邮件联系",
    },
  },
  en: {
    lang: "en",
    brand: "AXISX",
    brandSub: "HUMAN COMPUTE",
    nav: [
      ["Capabilities", "/services"],
      ["Delivery", "/delivery"],
      ["Work", "/work"],
      ["Meridian", "/meridian"],
      ["Quality", "/quality"],
      ["Roadmap", "/future"],
      ["Company", "/about"],
    ],
    contact: "Email us",
    language: "中文",
    home: {
      eyebrow: "MANAGED HUMAN COMPUTE · CHINA DELIVERY",
      title: "Turn specialist knowledge\ninto model-ready data",
      lead: "AxisX organizes university talent, domain specialists and full-chain QA into a managed delivery network for post-training, golden sets, agent evaluation and multimodal operations—from trial to accepted batch.",
      primary: "Brief a project",
      secondary: "See our work",
      proof: "We do not sell headcount. We deliver qualified, produced, reviewed and accepted outputs.",
      stackTitle: "Delivery system",
      stack: ["Task design & calibration", "Tiered talent qualification", "Production, QA & rework", "Accepted batches & feedback loop"],
      servicesTitle: "From data production to evaluation loops",
      servicesLead: "Specialists, workflow and quality control organized around the professional judgment models actually lack.",
      casesTitle: "Representative delivery",
      casesLead: "High-difficulty expert work and scaled multimodal production, managed through one operating layer.",
      processTitle: "Turn variable labor into managed delivery",
      processLead: "You calibrate the standard. We convert it into people, production and a quality system.",
      platformTitle: "Meridian: the operations layer behind delivery",
      platformBody: "An internal operations layer in active development, progressively bringing assignment, production, sampling, rework and batch tracking into one workflow. The interfaces shown combine current prototypes with real delivery scenarios; Meridian is not sold as standalone SaaS.",
    },
    common: {
      allCases: "View all work",
      learnMore: "Explore",
      contactTitle: "Start with a real task",
      contactBody: "Share an SOP, samples, volume and acceptance criteria. We will return an initial feasibility view within 24 hours.",
      email: "Email directly",
    },
  },
};

export const FUTURE = {
  en: {
    hero: {
      eyebrow: "ROADMAP / DIRECTION OF TRAVEL",
      title: "From managed delivery to an evaluation-native data system",
      lead: "AxisX is building toward a tighter connection between expert judgment, production evidence and model feedback. The roadmap below describes where the operating model is heading—not a list of features already available today.",
      tag: "DIRECTIONAL ROADMAP · AVAILABILITY VARIES BY PROJECT",
    },
    thesis: "The next data company will not be defined by the size of its workforce. It will be defined by how well it turns judgment into reusable, auditable model feedback.",
    horizons: [
      {
        no: "01",
        phase: "NOW",
        title: "Instrument the delivery layer",
        body: "Bring qualification, task versions, QA evidence, rework and batch acceptance into one operating record.",
        items: ["Project-specific qualification", "Versioned rules and edge cases", "Evidence-backed QA records"],
      },
      {
        no: "02",
        phase: "NEXT",
        title: "Build reusable calibration assets",
        body: "Turn high-value examples, rubrics, adjudications and failure patterns into maintained golden sets rather than one-off project residue.",
        items: ["Domain golden sets", "Rubric and judge calibration", "Reusable failure taxonomies"],
      },
      {
        no: "03",
        phase: "HORIZON",
        title: "Close the model feedback loop",
        body: "Connect expert sandboxes, synthetic-data validation and long-horizon agent evaluation to measurable model improvement.",
        items: ["Controlled expert workspaces", "Human-validated synthetic data", "Agent trajectory and judge reliability"],
      },
    ],
    bets: [
      ["Virtual scenes & simulation", "Scenario variation, state coverage and edge-case generation for embodied and multimodal systems, with human review where realism and semantics matter."],
      ["Synthetic-data validation", "Human screening, de-duplication, difficulty calibration and confirmation before generated data enters training."],
      ["Benchmarks & evaluation sets", "Versioned challenge sets, rubrics and judge calibration designed to reveal capability gaps rather than inflate a single score."],
      ["Expert sandboxes", "Controlled task environments with the right tools, context and access boundaries for specialist work."],
      ["Agent reliability", "Evaluation across task validity, tool use, trajectories, deliverables and judge behavior."],
      ["Evaluation-native data company", "A next-generation data partner connecting sourcing, production evidence, benchmarks and model feedback in one accountable system."],
    ],
  },
  zh: {
    hero: {
      eyebrow: "未来方向 / ROADMAP",
      title: "从托管交付走向\n评测原生的数据系统",
      lead: "子午象限正在把专家判断、生产证据与模型反馈连接得更紧密。以下内容说明我们正在推进的方向，而不是已经全面上线的功能清单。",
      tag: "方向性路线图 · 具体能力以项目实际为准",
    },
    thesis: "下一代数据公司，不由人力池规模定义，而由它能否把专业判断转化为可复用、可审计的模型反馈来定义。",
    horizons: [
      {
        no: "01",
        phase: "现在",
        title: "把交付过程变成可追踪记录",
        body: "将资格筛选、规则版本、质检证据、返修与批次验收接入同一条运营记录。",
        items: ["按项目资格筛选", "规则与边界案例版本化", "有证据的质检记录"],
      },
      {
        no: "02",
        phase: "下一步",
        title: "沉淀可复用的校准资产",
        body: "把高价值样本、量规、裁决与失败模式沉淀成持续维护的 Golden Set，而不是一次性交付残留。",
        items: ["垂直领域 Golden Set", "量规与评委校准", "可复用失败分类"],
      },
      {
        no: "03",
        phase: "长期方向",
        title: "闭合模型反馈回路",
        body: "让专家 Sandbox、合成数据验证与长程 Agent 评测能够对应到可衡量的模型改进。",
        items: ["受控专家作业环境", "人类验证的合成数据", "Agent 轨迹与评委可靠性"],
      },
    ],
    bets: [
      ["虚拟场景与仿真数据", "面向具身智能与多模态系统生成场景变化、状态覆盖与边界案例，并在真实性和语义环节保留人类复核。"],
      ["合成数据验证", "机器生成数据进入训练前，由人完成筛选、去重、难度校准与确认。"],
      ["Benchmark 与评测集", "持续维护版本化挑战集、量规与评委校准，以暴露能力缺口，而不是只优化单一分数。"],
      ["专家 Sandbox", "为专业任务提供适配工具、上下文与访问边界清晰的受控作业环境。"],
      ["Agent 可靠性", "同时评估任务有效性、工具调用、执行轨迹、交付物与评委行为。"],
      ["评测原生的新一代数商", "把人才供给、生产证据、Benchmark 与模型反馈连接成可追踪、可负责的下一代数据服务体系。"],
    ],
  },
};

export const PROCESS = {
  zh: [
    ["01", "任务拆解", "明确 SOP、样本、量规、体量、周期与验收逻辑。"],
    ["02", "试标校准", "以真实样本确认规则边界、人员适配与质检口径。"],
    ["03", "人才组队", "按学历、专业、经验与试标结果分层配置生产与 QA。"],
    ["04", "托管生产", "统一培训、排产、问答、进度、异常与版本管理。"],
    ["05", "质量闭环", "抽检、交叉复核、证据化返修与质检裁决。"],
    ["06", "批次交付", "按验收标准提交结果，并将反馈固化进下一批规则。"],
  ],
  en: [
    ["01", "Task framing", "Define SOP, samples, rubric, volume, timeline and acceptance logic."],
    ["02", "Trial & calibration", "Use real samples to test rule boundaries, talent fit and QA standards."],
    ["03", "Team design", "Tier production and QA by education, domain, experience and trial results."],
    ["04", "Managed production", "Own training, allocation, Q&A, progress, exceptions and version control."],
    ["05", "Quality loop", "Sampling, cross-review, evidence-based rework and QA adjudication."],
    ["06", "Batch delivery", "Submit against acceptance criteria and convert feedback into the next rule set."],
  ],
};

export const QUALITY = {
  zh: [
    ["资格门槛", "人员通过真实任务测试后进入生产，而不是仅按简历入池。"],
    ["金标与校准", "将客户样本、边界案例与反馈固化成持续更新的校准集。"],
    ["分层质检", "运营 QA 与领域复核按任务难度组合，避免所有任务使用同一套检查。"],
    ["证据化返修", "不合格项必须指向明确规则、样本或量规，降低主观来回。"],
    ["数据边界", "按项目约定使用指定平台、账号、权限与保密要求，不留存或挪用数据。"],
    ["版本闭环", "规则、问题、反馈与返修结果进入下一批生产版本。"],
  ],
  en: [
    ["Qualification gates", "Contributors enter production by passing real task tests—not by résumé alone."],
    ["Gold calibration", "Client examples, edge cases and feedback become a continuously updated calibration set."],
    ["Tiered QA", "Operational QA and domain review are combined according to task difficulty."],
    ["Evidence-based rework", "Every rejection points to a written rule, example or rubric criterion."],
    ["Data boundaries", "Client-designated platforms, accounts, permissions and confidentiality rules govern access."],
    ["Version loop", "Rules, questions, feedback and rework outcomes become the next production version."],
  ],
};

export const DOMAINS = {
  zh: ["计算机与 AI", "数学与物理科学", "金融、经济与风险", "生命科学", "法学与合规", "工程与建成环境", "语言与语言学", "商业与管理"],
  en: ["Computer science & AI", "Mathematics & physical sciences", "Finance, economics & risk", "Life sciences", "Legal studies & compliance", "Engineering & built environment", "Language & linguistics", "Business & management"],
};
