export const SITE_EMAIL = "kevin@ziwuxx.com";

export const STATS = {
  zh: [
    ["102+", "海内外高校与研究机构协作关系"],
    ["3,000+", "经筛选的 AI 数据与评测人才网络"],
    ["2,000+", "本科、ML、软件与工程人才"],
    ["1,000+", "硕博、医生、律师与垂类专家"],
  ],
  en: [
    ["102+", "University & research relationships"],
    ["3,000+", "Screened AI data & evaluation network"],
    ["2,000+", "Undergraduate, ML, software & engineering talent"],
    ["1,000+", "Graduate, medical, legal & domain specialists"],
  ],
};

export const NETWORK_PROOF = {
  zh: {
    asOf: "NETWORK SNAPSHOT / 2026.09 · 滚动更新",
    note: "数字采用可验证的保守下限，用来说明我们能够触达和筛选的组织与人才基础，不等同于同一时间全部投入项目的并发人数。",
    rules: [
      ["院校关系", "统计已建立的人才推荐、项目协作或学术交流关系；不把一次性名单计为合作院校。"],
      ["专家网络", "统计已完成背景归档、可进入项目资格筛选的硕博、医生、律师与垂类人员。"],
      ["动态更新", "人员仍需通过具体任务测试、保密要求与校准；网络随资格状态和在执行项目滚动更新。"],
    ],
  },
  en: {
    asOf: "NETWORK SNAPSHOT / 2026.09 · ROLLING UPDATE",
    note: "Figures are conservative verified floors describing institutional reach and addressable qualified talent—not simultaneous deployed headcount.",
    rules: [
      ["Institutional reach", "Counts established talent, project or academic relationships; one-off contact lists are not treated as university partnerships."],
      ["Specialist network", "Counts graduate, medical, legal and vertical-domain profiles documented for task-specific qualification."],
      ["Rolling qualification", "Every contributor still passes project tests, confidentiality controls and calibration; status updates with active programs."],
    ],
  },
};

export const PRODUCT_SYSTEMS = {
  zh: [
    {
      id: "01",
      label: "EXPERT KNOWLEDGE SYSTEMS",
      title: "专家知识系统",
      body: "把金融、法律、医学、地学与教育中的专业判断，转化为有来源、有边界、可独立复核的训练数据与 Golden Set。",
      output: "交付：任务集、专家参考、证据跨度、量规、裁决记录",
      items: ["受监管领域长上下文", "垂类知识工作流", "专家双评与来源级证据"],
      tone: "expert",
    },
    {
      id: "02",
      label: "AGENT & POST-TRAINING DATA",
      title: "Agent 与后训练数据",
      body: "记录计划、工具调用、观察、回退和停止条件，把过程失败转化为可诊断、可训练的行为证据。",
      output: "交付：关键节点、失败分类、偏好对、修正轨迹、评委复核",
      items: ["长程工具使用轨迹", "失败归因与更优路径", "SFT、偏好、批评与改写"],
      tone: "agent",
    },
    {
      id: "03",
      label: "EXECUTABLE BENCHMARK ENGINEERING",
      title: "可执行 Benchmark 工程",
      body: "围绕 STEM、MLE / MLS、ProgramBench 与 FrontierSWE 构造原创任务、隔离环境、验证器和持续评测版本。",
      output: "交付：原创任务、环境、Golden Run、验证器、运行与版本报告",
      items: ["STEM 原创 Challenge Set", "可复现实验与方法评测", "程序行为与仓库级软件工程"],
      tone: "benchmark",
    },
  ],
  en: [
    {
      id: "01",
      label: "EXPERT KNOWLEDGE SYSTEMS",
      title: "Expert knowledge systems",
      body: "Turn judgment across finance, legal, medical, geoscience and education into source-grounded, bounded and independently reviewable training data and golden sets.",
      output: "Deliverables: task set, expert reference, evidence spans, rubric and adjudication record",
      items: ["Regulated-domain long context", "Vertical knowledge workflows", "Dual expert review and source evidence"],
      tone: "expert",
    },
    {
      id: "02",
      label: "AGENT & POST-TRAINING DATA",
      title: "Agent and post-training data",
      body: "Capture plans, tool calls, observations, recovery and stopping conditions—then convert process failures into diagnostic and trainable behavioral evidence.",
      output: "Deliverables: critical nodes, failure taxonomy, preference pairs, corrected traces and judge review",
      items: ["Long-horizon tool-use traces", "Root cause and improved paths", "SFT, preference, critique and rewrite"],
      tone: "agent",
    },
    {
      id: "03",
      label: "EXECUTABLE BENCHMARK ENGINEERING",
      title: "Executable benchmark engineering",
      body: "Build original tasks, isolated environments, verifiers and maintained releases across STEM, MLE / MLS, ProgramBench and FrontierSWE-style work.",
      output: "Deliverables: original tasks, environment, golden run, verifier, run evidence and release report",
      items: ["Original STEM challenge sets", "Reproducible experiments and method evaluation", "Program behavior and repository engineering"],
      tone: "benchmark",
    },
  ],
};

const servicesZh = [
  {
    id: "01",
    title: "受监管领域专家数据",
    label: "Domain expert data",
    body: "面向金融、法律与医学知识任务，构建有来源、有量规、可复核的训练数据与 Golden Set。",
    items: ["长上下文任务与专家答案", "证据定位、引用与事实核验", "双评、领域复核与裁决"],
  },
  {
    id: "02",
    title: "STEM 原创难题与 Challenge Set",
    label: "Expert problem authoring",
    body: "由数学、物理、化学、生物与计算机专家构造原创、不可直接检索、答案可验证的前沿推理任务。",
    items: ["高难度原创出题与参考解", "程序化验证器与唯一性检查", "模型试跑、难度校准与污染筛查"],
  },
  {
    id: "03",
    title: "模型后训练与 Agent 轨迹",
    label: "Post-training & traces",
    body: "把模型的计划、工具调用、观察、修正与最终结果转化为可训练、可诊断的行为证据。",
    items: ["SFT、偏好、批评与改写", "多步工具轨迹与关键节点", "失败归因与更优路径示范"],
  },
  {
    id: "04",
    title: "MLE-Bench / MLS-Bench 交付",
    label: "ML engineering & science",
    body: "围绕数据准备、实验、模型改进与方法泛化，组织可复现的机器学习工程与研究型评测。",
    items: ["任务构造与环境检查", "实验记录、产物与指标审阅", "独立复跑与科学性裁决"],
  },
  {
    id: "05",
    title: "ProgramBench 与 FrontierSWE",
    label: "Executable software evaluation",
    body: "从行为级程序重建到真实仓库的长程工程任务，构造可执行、可复现、可裁决的软件智能评测。",
    items: ["行为规格、隐藏测试与等价性", "原创仓库级任务与隔离环境", "补丁、日志、测试与长程轨迹审阅"],
  },
  {
    id: "06",
    title: "Benchmark 托管交付",
    label: "Managed benchmark ops",
    body: "按国际一线数据合作方的交付结构，统一管理试题、专家、环境、运行、质检、返修与批次验收。",
    items: ["任务与人员资格门槛", "盲审、交叉复核与裁决", "版本化数据与可审计证据"],
  },
];

const servicesEn = [
  {
    id: "01",
    title: "Expert data for regulated domains",
    label: "Domain expert data",
    body: "Source-grounded training data and golden sets for financial, legal and medical knowledge work, built to remain reviewable.",
    items: ["Long-context tasks & expert answers", "Evidence, citation & fact checks", "Dual review, specialist QA & adjudication"],
  },
  {
    id: "02",
    title: "Original STEM challenge sets",
    label: "Expert problem authoring",
    body: "Original, non-searchable and verifiable frontier reasoning tasks authored across mathematics, physics, chemistry, biology and computer science.",
    items: ["Expert problem authoring & reference derivations", "Programmatic verifiers & uniqueness checks", "Model pilots, difficulty calibration & contamination screening"],
  },
  {
    id: "03",
    title: "Post-training & agent trajectories",
    label: "Post-training & traces",
    body: "Plans, tool calls, observations, corrections and final outputs captured as trainable and diagnostic behavioral evidence.",
    items: ["SFT, preference, critique & rewrite", "Multi-step traces & critical decisions", "Failure attribution & improved trajectories"],
  },
  {
    id: "04",
    title: "MLE-Bench / MLS-Bench programs",
    label: "ML engineering & science",
    body: "Reproducible evaluation operations spanning data preparation, experimentation, model improvement and method generalization.",
    items: ["Task construction & environment checks", "Experiment, artifact & metric review", "Independent reruns & scientific adjudication"],
  },
  {
    id: "05",
    title: "ProgramBench & FrontierSWE",
    label: "Executable software evaluation",
    body: "Executable, reproducible and adjudicable software-intelligence evaluation—from behavioral program reconstruction to long-horizon repository work.",
    items: ["Behavior specs, hidden tests & equivalence", "Original repository tasks & isolated environments", "Patch, logs, tests & long-horizon trace review"],
  },
  {
    id: "06",
    title: "Managed benchmark delivery",
    label: "Managed benchmark ops",
    body: "An operating model organized around enterprise delivery requirements—across tasks, experts, environments, runs, QA and acceptance.",
    items: ["Task & contributor qualification", "Blind review, cross-checks & adjudication", "Versioned data & auditable evidence"],
  },
];

export const SERVICES = { zh: servicesZh, en: servicesEn };

export const CASES = [
  {
    slug: "financial-reasoning",
    image: "/meridian/v10/zh/finance.jpg",
    imageEn: "/meridian/v10/en/finance.jpg",
    video: "/meridian/clips/finance-zh.mp4",
    videoEn: "/meridian/clips/finance-en.mp4",
    tone: "teal",
    metrics: {
      zh: [["≈4.2K", "推理任务"], ["48–64K", "上下文"], [">97%", "证据对齐"]],
      en: [["≈4.2K", "reasoning tasks"], ["48–64K", "context"], [">97%", "evidence alignment"]],
    },
    zh: {
      tag: "金融 · 风控与研究",
      title: "金融长上下文推理与证据标注",
      summary: "让研究、估值、风控与合规判断同时保留答案、依据、边界与审核状态。",
      body: "某金融模型团队需要验证模型能否在跨年度财报、授信政策、行业研究和风险条款之间完成有依据的判断。项目先建立文档层级、时间边界与引用协议，再由金融背景作者构造研究、估值、风控与合规问题；独立复核员只在隐藏原始判断的条件下检查结论和证据跨度。展示数字为代表性脱敏批次口径，客户身份、材料内容与部分规模已区间化。",
      deliveryModel: "金融专家 × 来源证据 × 独立复核",
      proof: ["跨年度、多来源长上下文与引用定位", "结论、证据、反证与不确定边界一体交付", "高风险分歧进入金融专家裁决记录"],
      profile: [["对象", "财报、授信政策、行业研究与风险条款组成的受控材料包"], ["执行", "金融作者出题与作答，运营 QA 校验协议，独立专家复核证据和专业判断"], ["规模", "代表批次约 4,200 个推理任务；单任务上下文 48K–64K tokens"], ["结果", "证据跨度验收高于 97%；高风险分歧全部形成可回溯裁决记录"]],
    },
    en: {
      tag: "Finance · Risk & research",
      title: "Financial reasoning with source evidence",
      summary: "Research, valuation, risk and compliance judgments delivered with answers, evidence, boundaries and review state.",
      body: "A financial-model team needed to test whether the model could reason across multi-year statements, credit policy, sector research and risk clauses without losing evidentiary grounding. We defined the document hierarchy, temporal scope and citation protocol before finance-qualified authors constructed research, valuation, risk and compliance tasks. Independent reviewers assessed conclusions and evidence spans without seeing the original judgment. Figures shown are from a representative sanitized batch; identities, source material and selected volumes have been removed or banded.",
      deliveryModel: "Finance specialists × source evidence × independent review",
      proof: ["Multi-year, multi-source context with citation spans", "Answer, evidence, counter-evidence and uncertainty delivered together", "High-risk disagreement routed to finance adjudication"],
      profile: [["Object", "Controlled packs spanning statements, credit policy, sector research and risk clauses"], ["Execution", "Finance authors, protocol QA and independent evidence review operated as separate roles"], ["Scale", "Representative batch of approximately 4,200 reasoning tasks at 48K–64K tokens each"], ["Outcome", "Evidence-span acceptance above 97%; all high-risk disputes retained an auditable ruling"]],
    },
  },
  {
    slug: "legal-long-context",
    image: "/meridian/v10/zh/legal.jpg",
    imageEn: "/meridian/v10/en/legal.jpg",
    video: "/meridian/clips/legal-zh.mp4",
    videoEn: "/meridian/clips/legal-en.mp4",
    tone: "gold",
    metrics: { zh: [["≈1.3K", "长文档任务"], ["3", "审阅层级"], [">96%", "引用一致"]], en: [["≈1.3K", "long-doc tasks"], ["3", "review layers"], [">96%", "citation agreement"]] },
    zh: {
      tag: "法律 · 合同与检索",
      title: "法律长文档审阅与引用级评测",
      summary: "围绕合同、法规与案件材料构建可验证任务，而不是只给出一个无出处的结论。",
      body: "某法律智能项目需要评估模型在主协议、附件、监管材料与往来修订之间定位冲突和形成备忘录的能力。法律人员先锁定法域、时间和适用文本版本，再执行条款识别、冲突分析、检索型问答与引用核验；有实质影响的分歧进入盲审和裁决。展示为脱敏后的代表交付结构，不构成法律意见。",
      deliveryModel: "法域边界 × 引用级证据 × 盲审裁决",
      proof: ["合同、附件、法规与修订记录联合审阅", "每个实质性主张绑定文本版本与引用跨度", "专业分歧保留法域、理由与最终裁决"],
      profile: [["对象", "主协议、补充协议、监管材料与历史修订组成的法律材料包"], ["执行", "法域限定、条款抽取、冲突聚类、引用核验和独立法律复核"], ["规模", "代表批次约 1,300 个长文档任务，采用三层审阅与 A/B 盲审"], ["结果", "实质性主张的引用一致率高于 96%，版本冲突均进入可追溯问题单"]],
    },
    en: {
      tag: "Legal · Contracts & research",
      title: "Legal review with citation-level evaluation",
      summary: "Verifiable tasks across contracts, regulations and case material—not unsupported conclusions.",
      body: "A legal-intelligence program needed to evaluate conflict detection and memo drafting across a master agreement, schedules, regulatory material and revision history. Legal specialists fixed jurisdiction, time and controlling-text versions before clause extraction, conflict analysis, research QA and citation checks. Material disagreement entered blind review and adjudication. This is a sanitized representative delivery structure and does not constitute legal advice.",
      deliveryModel: "Jurisdiction scope × citation evidence × blind adjudication",
      proof: ["Contracts, schedules, regulation and revision history reviewed together", "Every material claim tied to a text version and citation span", "Jurisdiction, rationale and ruling retained for disputes"],
      profile: [["Object", "Legal packs spanning agreements, amendments, regulation and revision history"], ["Execution", "Jurisdiction scoping, clause extraction, conflict clustering, citation QA and independent legal review"], ["Scale", "Representative batch of approximately 1,300 long-document tasks with three review layers"], ["Outcome", "Citation agreement above 96% for material claims; version conflicts remained traceable"]],
    },
  },
  {
    slug: "medical-evidence",
    image: "/meridian/v10/zh/medical.jpg",
    imageEn: "/meridian/v10/en/medical.jpg",
    video: "/meridian/clips/medical-zh.mp4",
    videoEn: "/meridian/clips/medical-en.mp4",
    tone: "red",
    metrics: { zh: [["≈3.6K", "证据单元"], ["2×", "医学复核"], ["0", "个人健康信息"]], en: [["≈3.6K", "evidence units"], ["2×", "medical review"], ["0", "PHI"]] },
    zh: {
      tag: "医学 · 循证与安全",
      title: "医学证据抽取与安全边界评测",
      summary: "把文献、指南与病例型材料转化为结构化证据、参考答案和风险边界。",
      body: "某医学知识模型评测以已去标识化材料、临床指南和公开文献为输入，要求模型区分研究结论、适用人群、证据等级与不能越过的安全边界。医学背景人员完成证据抽取和指南一致性判断，高风险回答由两名医学复核员独立审阅，并记录升级原因、来源版本和置信度。展示不含真实患者信息，也不用于临床诊断。",
      deliveryModel: "医学资格筛选 × 循证溯源 × 安全升级",
      proof: ["研究人群、干预、结局与证据等级结构化", "高风险结论执行双重医学复核", "来源、置信度、安全边界与升级原因一并保留"],
      profile: [["对象", "去标识化病例型材料、指南章节与同行评议文献"], ["执行", "PICO 证据抽取、指南一致性、回答安全性与双医学复核"], ["规模", "代表批次约 3,600 个证据单元，全流程不接触个人健康信息"], ["结果", "高风险输出 100% 进入双评；证据来源和安全升级路径可逐项回溯"]],
    },
    en: {
      tag: "Medical · Evidence & safety",
      title: "Medical evidence abstraction and safety evaluation",
      summary: "Literature, guidance and case-style material converted into structured evidence, references and safety boundaries.",
      body: "A medical-knowledge evaluation used de-identified case-style material, clinical guidelines and published literature to test whether the model could separate findings, population scope, evidence strength and safety boundaries. Medically qualified contributors abstracted evidence and reviewed guideline consistency; high-risk answers received two independent medical reviews with source version, confidence and escalation rationale retained. No real patient information is shown and the work does not provide diagnosis.",
      deliveryModel: "Medical qualification × evidence provenance × safety escalation",
      proof: ["Population, intervention, outcome and evidence grade structured", "Dual medical review for high-risk conclusions", "Provenance, confidence, safety boundary and escalation retained"],
      profile: [["Object", "De-identified case-style material, guideline sections and peer-reviewed literature"], ["Execution", "PICO abstraction, guideline consistency, safety evaluation and dual medical review"], ["Scale", "Representative batch of approximately 3,600 evidence units with zero PHI exposure"], ["Outcome", "All high-risk outputs entered dual review with fully traceable sources and escalation paths"]],
    },
  },
  {
    slug: "stem-challenge-sets",
    image: "/meridian/v10/zh/stem.jpg",
    imageEn: "/meridian/v10/en/stem.jpg",
    video: "/meridian/clips/stem-zh.mp4",
    videoEn: "/meridian/clips/stem-en.mp4",
    tone: "lime",
    metrics: { zh: [["≈1.2K", "原创任务"], ["5", "STEM 领域"], ["6–18%", "模型通过率"]], en: [["≈1.2K", "original tasks"], ["5", "STEM domains"], ["6–18%", "model pass rate"]] },
    zh: {
      tag: "STEM · 原创难题",
      title: "高难度 STEM Challenge Set 设计",
      summary: "把研究级知识、多步推导与可验证答案组织成模型无法靠检索直接解决的原创任务。",
      body: "某前沿推理评测需要一组无法通过搜索或模板迁移直接作答的原创问题。我们先定义目标能力和预期失败模式，再由数学、物理、化学、生物与计算机专家提交题面、完整推导、评分量规和验证逻辑。另一名专家独立复算；模型试跑、相似性检索与程序化验证共同排除歧义、污染和偶然猜中。规模与通过率为代表性脱敏批次区间。本能力对齐前沿科学推理 Benchmark 的任务方法，不代表与任何公开基准存在官方合作。",
      deliveryModel: "原创出题 × 参考解推导 × 验证器与难度校准",
      proof: ["跨数学、物理、化学、生物与计算机科学", "题目、参考解、量规与验证器成套交付", "独立复算、模型试跑与污染风险筛查"],
      profile: [["对象", "面向指定能力缺口的原创、不可直接检索 STEM 难题"], ["执行", "专家出题、独立复算、验证器构建、模型试跑与难度分层"], ["规模", "代表批次约 1,200 道原创任务，覆盖五个 STEM 学科"], ["结果", "目标模型通过率稳定在 6%–18% 区间；歧义题和可检索题在发布前剔除"]],
      flagship: {
        label: "旗舰案例档案 / STEM",
        thesis: "难度不是把知识点变偏，而是让任务稳定暴露目标能力缺口，同时保持题意清晰、答案确定、推导可复算。",
        workflow: [["能力切片", "从模型错误簇反推需要隔离验证的知识与推理能力。"], ["原创构造", "专家同时提交题面、参考推导、评分量规与验证逻辑。"], ["独立复算", "第二位专家不查看原解，验证题意、答案与关键中间结论。"], ["模型压力测试", "使用多次试跑识别捷径、歧义、偶然猜中与失效难度。"], ["版本发布", "仅将通过原创性、可验证性和难度门槛的任务纳入批次。"]],
        failureGates: ["存在多解或隐含假设未写明", "参考推导无法由独立专家复算", "公开检索或表面改写即可命中答案", "验证器只检查最终格式而未覆盖核心推理"],
        handoff: ["题目与能力标签", "专家参考解与关键步骤", "评分量规及程序化验证器", "独立复算、模型试跑与版本记录"],
        use: "验收后的任务可进入私有 Challenge Set、能力回归测试或针对性后训练设计；具体使用方式由客户的模型阶段与授权边界决定。",
      },
    },
    en: {
      tag: "STEM · Original challenges",
      title: "Expert-authored STEM challenge sets",
      summary: "Original tasks that combine advanced knowledge, multi-step derivation and verifiable answers beyond direct retrieval.",
      body: "A frontier-reasoning evaluation required original problems that could not be answered through search or template transfer. We defined the target capability and expected failure mode before specialists across mathematics, physics, chemistry, biology and computer science submitted prompts, complete derivations, rubrics and validation logic. A second specialist solved each task independently; model pilots, similarity search and programmatic checks removed ambiguity, contamination and accidental guessability. Volumes and pass rates are banded from a representative sanitized batch. This capability aligns to frontier scientific-reasoning methods and does not imply official affiliation with a public benchmark.",
      deliveryModel: "Original authoring × reference derivation × verifier-led calibration",
      proof: ["Mathematics, physics, chemistry, biology and computer science", "Problem, reference, rubric and verifier delivered together", "Independent solve, model pilot and contamination-risk screen"],
      profile: [["Object", "Original, non-searchable STEM problems aimed at a specified capability gap"], ["Execution", "Expert authoring, independent solve, verifier construction, model pilots and difficulty tiers"], ["Scale", "Representative batch of approximately 1,200 original tasks across five STEM disciplines"], ["Outcome", "Target-model pass rates held between 6% and 18%; ambiguous and searchable items were removed pre-release"]],
      flagship: {
        label: "FLAGSHIP CASE FILE / STEM",
        thesis: "Difficulty is not obscurity. A valid challenge must isolate the intended capability gap while keeping the prompt clear, the answer determinate and the derivation independently reproducible.",
        workflow: [["Capability slice", "Work backward from model error clusters to the knowledge and reasoning boundary that needs isolation."], ["Original authoring", "The specialist submits the problem, full reference, scoring rubric and validation logic as one unit."], ["Independent solve", "A second specialist verifies interpretation, answer and critical intermediate results without seeing the first solution."], ["Model stress test", "Repeated pilots expose shortcuts, ambiguity, accidental success and difficulty collapse."], ["Version release", "Only tasks that clear originality, verifiability and difficulty gates enter the accepted batch."]],
        failureGates: ["Multiple valid answers or unstated assumptions", "Reference derivation cannot be independently reproduced", "Public retrieval or surface rewriting reveals the answer", "Verifier checks formatting without covering the core reasoning"],
        handoff: ["Problem and capability labels", "Expert reference and critical steps", "Scoring rubric and programmatic verifier", "Independent solve, model-pilot and version records"],
        use: "Accepted tasks can support a private challenge set, capability regression testing or targeted post-training design. The final use depends on model stage and the agreed data rights.",
      },
    },
  },
  {
    slug: "agent-trajectory",
    image: "/meridian/v10/zh/trajectory.jpg",
    imageEn: "/meridian/v10/en/trajectory.jpg",
    video: "/meridian/clips/trajectory-zh.mp4",
    videoEn: "/meridian/clips/trajectory-en.mp4",
    tone: "blue",
    metrics: { zh: [["≈2.8K", "长程轨迹"], ["18", "平均步骤"], ["7", "失败类型"]], en: [["≈2.8K", "long traces"], ["18", "avg. steps"], ["7", "failure classes"]] },
    zh: {
      tag: "大模型 · Agent",
      title: "长程 Agent 轨迹与失败归因",
      summary: "从任务输入、计划与工具调用到最终交付物，逐节点审阅 Agent 行为。",
      body: "某工具型 Agent 在文件、浏览器、代码和结构化数据之间完成长程任务，最终结果偶尔正确，但中间过程包含不稳定重试和错误来源选择。项目完整记录行动—观察链，评测员定位关键决策、工具参数、回退、自检与停止条件，并将问题区分为任务、规划、工具、执行、事实、交付物或评委层错误；高价值失败再转写为可用于后训练的修正轨迹。",
      deliveryModel: "关键节点标注 × 双路审阅 × 失败分类",
      proof: ["完整行动—观察—修正链路", "过程质量与结果质量分离", "失败原因对应可训练修正轨迹"],
      profile: [["对象", "跨文件、浏览器、代码与结构化工具的长程 Agent 运行"], ["执行", "关键节点标注、A/B 独立复核、失败归因和更优轨迹重写"], ["规模", "代表批次约 2,800 条轨迹，平均 18 个步骤并覆盖 6 类工具"], ["结果", "关键节点覆盖率达到 100%；高价值失败形成可直接进入后训练的修正样本"]],
      flagship: {
        label: "旗舰案例档案 / AGENT",
        thesis: "最终答案正确并不足以证明 Agent 可靠。真正需要评估的是它是否选择了正确的信息、工具、顺序与停止条件。",
        workflow: [["运行固化", "锁定任务、环境、工具版本与行动—观察序列。"], ["关键节点识别", "标记不可逆决策、外部调用、错误恢复与最终提交节点。"], ["双路复核", "独立评测员分别判断过程质量、结果质量和错误归属。"], ["分歧裁决", "对规划、工具、事实、执行或评委层分歧保留理由与裁决。"], ["轨迹修正", "将高价值失败重写为最小必要改动的可训练示范。"]],
        failureGates: ["结果正确但使用了错误或不可验证的来源", "无效重试掩盖了规划或工具选择错误", "中间状态已失败但 Agent 未触发恢复", "停止条件过早或提交物未满足任务验收"],
        handoff: ["原始行动—观察轨迹", "关键节点与失败类型", "A/B 复核及裁决记录", "修正轨迹与训练适用标签"],
        use: "轨迹包可用于 Agent 回归评测、失败模式分析、SFT 或偏好数据设计；进入训练前仍需按客户策略确认采样、权重与数据许可。",
      },
    },
    en: {
      tag: "LLM · Agents",
      title: "Long-horizon agent trajectories and failure attribution",
      summary: "Node-level review from task intake and planning through tool use and final deliverables.",
      body: "A tool-using agent completed long-horizon work across files, browsers, code and structured data. Some final outputs were correct despite unstable retries and poor source selection. We retained the complete action–observation chain, then evaluated critical decisions, tool parameters, recovery, self-checks and stopping conditions. Failures were separated across task, plan, tool, execution, factuality, deliverable and judge layers; high-value failures were rewritten into improved post-training trajectories.",
      deliveryModel: "Critical-node annotation × dual review × failure taxonomy",
      proof: ["Complete action–observation–correction chain", "Process quality separated from outcome quality", "Trainable corrections tied to root cause"],
      profile: [["Object", "Long-horizon agent runs across files, browsers, code and structured tools"], ["Execution", "Critical-node annotation, independent A/B review, root-cause attribution and trajectory correction"], ["Scale", "Representative batch of approximately 2,800 traces averaging 18 steps across six tool classes"], ["Outcome", "All critical nodes received review; high-value failures became post-training-ready corrections"]],
      flagship: {
        label: "FLAGSHIP CASE FILE / AGENT",
        thesis: "A correct final answer does not establish agent reliability. The operating question is whether the agent selected the right information, tools, sequence and stopping condition.",
        workflow: [["Freeze the run", "Lock the task, environment, tool versions and action–observation sequence."], ["Identify critical nodes", "Mark irreversible decisions, external calls, recovery attempts and final submission."], ["Independent review", "Separate reviewers judge process quality, outcome quality and root-cause attribution."], ["Adjudicate disagreement", "Retain the rationale and ruling for plan, tool, factual, execution or judge-layer disputes."], ["Correct the trace", "Rewrite high-value failures as minimal, trainable changes rather than idealized demonstrations."]],
        failureGates: ["Correct output built on the wrong or unverifiable source", "Repeated retries obscure a planning or tool-selection failure", "A failed intermediate state does not trigger recovery", "Premature stopping or an incomplete final deliverable"],
        handoff: ["Original action–observation trace", "Critical nodes and failure taxonomy", "A/B review and adjudication record", "Corrected trajectory with training-use labels"],
        use: "Trace packages can support agent regression evaluation, failure analysis, SFT or preference-data design. Sampling, weighting and data rights are confirmed before training use.",
      },
    },
  },
  {
    slug: "mle-mls-benchmark",
    image: "/meridian/v10/zh/mle.jpg",
    imageEn: "/meridian/v10/en/mle.jpg",
    video: "/meridian/clips/mle-zh.mp4",
    videoEn: "/meridian/clips/mle-en.mp4",
    tone: "violet",
    metrics: { zh: [["420+", "实验运行"], ["3", "隔离环境"], [">95%", "复跑一致"]], en: [["420+", "experiment runs"], ["3", "isolated envs"], [">95%", "rerun match"]] },
    zh: {
      tag: "ML 工程与研究",
      title: "MLE-Bench / MLS-Bench 型评测运营",
      summary: "从完成机器学习任务，进一步评估实验可复现性、方法改进与泛化证据。",
      body: "某模型工程评测需要同时判断候选系统能否完成训练任务，以及其方法改进是否能够独立复现。我们把数据版本、容器镜像、基线、预算、评分器和产物格式固定进任务包；运行后审阅实验日志、指标计算、消融与跨设置泛化，并由独立工程师在隔离环境中复跑关键结论。",
      deliveryModel: "环境复现 × ML 专家审阅 × 独立复跑",
      proof: ["任务、环境、数据与评分器成套交付", "实验记录和产物可追溯", "工程完成度与科学有效性分层评测"],
      profile: [["对象", "含数据、基线、训练预算、评分器与提交协议的 ML 任务包"], ["执行", "环境锁定、实验运行、产物检查、科学性审阅与独立复跑"], ["规模", "代表项目 420+ 次实验运行，覆盖三套隔离环境与多类加速配置"], ["结果", "关键运行复跑一致率高于 95%；指标异常均能回到日志、数据或实现证据"]],
    },
    en: {
      tag: "ML engineering & science",
      title: "MLE-Bench / MLS-Bench-style evaluation operations",
      summary: "Evaluate task completion, experiment reproducibility, method improvement and evidence of generalization.",
      body: "An ML-engineering evaluation needed to determine both whether candidates could complete the training task and whether claimed improvements would reproduce independently. We fixed data versions, container images, baselines, budgets, graders and artifact schemas inside each task pack. Run review covered logs, metric computation, ablations and cross-setting generalization, with critical claims rerun by an independent engineer in an isolated environment.",
      deliveryModel: "Environment reproduction × ML expert review × independent rerun",
      proof: ["Task, environment, data and grader delivered together", "Experiments and artifacts remain traceable", "Engineering completion separated from scientific validity"],
      profile: [["Object", "ML task packs with data, baseline, compute budget, grader and submission protocol"], ["Execution", "Environment locking, runs, artifact checks, scientific review and independent reruns"], ["Scale", "More than 420 experiment runs across three isolated environments and several accelerator profiles"], ["Outcome", "Critical-run reproduction exceeded 95%; metric anomalies remained traceable to logs, data or implementation"]],
    },
  },
  {
    slug: "programbench-reconstruction",
    image: "/meridian/v10/zh/program.jpg",
    imageEn: "/meridian/v10/en/program.jpg",
    video: "/meridian/clips/program-zh.mp4",
    videoEn: "/meridian/clips/program-en.mp4",
    tone: "gold",
    metrics: { zh: [["360+", "程序任务"], ["26–140", "隐藏测试"], [">98%", "评分稳定"]], en: [["360+", "program tasks"], ["26–140", "hidden tests"], [">98%", "grader stability"]] },
    zh: {
      tag: "ProgramBench · 行为重建",
      title: "可执行程序行为重建评测",
      summary: "只给行为规格和黑盒参考，让模型重建完整、兼容且能通过隐藏测试的程序。",
      body: "某代码模型评测需要避开短函数补全，转向可安装、可交互、包含状态和异常语义的完整程序重建。任务作者定义公开行为规格与黑盒参考；验证工程师从接口、文件、错误、状态、边界和并发六个维度编写隐藏测试；候选提交在隔离环境中安装、运行并复测，评分器稳定性另由独立人员验证。",
      deliveryModel: "黑盒规格 × 隐藏测试 × 评分器复验",
      proof: ["从行为规格而非源代码重建完整程序", "接口、状态、错误与边界测试组合", "任务作者、验证工程师与评分器复验角色分离"],
      profile: [["对象", "具备 CLI、文件读写、持久状态和错误语义的完整程序"], ["执行", "黑盒规格设计、参考实现锁定、隐藏测试构造与隔离环境运行"], ["规模", "代表批次 360+ 个任务，每项配置 26–140 个隐藏行为测试"], ["结果", "评分器跨环境一致性高于 98%；偶然通过和实现泄漏在验收前剔除"]],
    },
    en: {
      tag: "ProgramBench · Behavioral reconstruction",
      title: "Executable program-reconstruction evaluation",
      summary: "Models receive behavioral specifications and a black-box reference, then rebuild a complete compatible program against hidden tests.",
      body: "A coding-model evaluation moved beyond short function completion into installable, interactive programs with state and error semantics. Task authors defined public behavior and locked a black-box reference. Verification engineers built hidden tests across interface, files, errors, state, boundaries and concurrency. Candidate submissions were installed, executed and retested in isolation, while independent reviewers checked grader stability.",
      deliveryModel: "Black-box specification × hidden tests × grader replication",
      proof: ["Reconstruct complete programs from behavior rather than source", "Interface, state, error and boundary tests combined", "Author, verifier and grader-replication roles separated"],
      profile: [["Object", "Complete programs with CLI, file I/O, persistent state and error semantics"], ["Execution", "Black-box specification, reference lock, hidden-test construction and isolated execution"], ["Scale", "Representative batch of 360+ tasks with 26–140 hidden behavioral tests each"], ["Outcome", "Cross-environment grader agreement above 98%; accidental passes and leakage removed pre-acceptance"]],
    },
  },
  {
    slug: "frontier-swe",
    image: "/meridian/v10/zh/swe.jpg",
    imageEn: "/meridian/v10/en/swe.jpg",
    video: "/meridian/clips/swe-zh.mp4",
    videoEn: "/meridian/clips/swe-en.mp4",
    tone: "violet",
    metrics: { zh: [["310+", "仓库任务"], ["2–14", "变更文件"], [">96%", "CI 可复现"]], en: [["310+", "repository tasks"], ["2–14", "files changed"], [">96%", "CI reproducibility"]] },
    zh: {
      tag: "DeepSWE · FrontierSWE",
      title: "长程仓库级软件工程评测",
      summary: "把真实仓库探索、多文件实现、回归保护与环境验证组织成可裁决的长程任务。",
      body: "某软件智能项目需要衡量模型能否理解陌生仓库、定位跨模块缺陷并提交不会破坏既有行为的完整补丁。任务从已授权仓库快照中脱敏构造，固定依赖、容器和基准提交；候选运行保留检索、编辑、测试与回退轨迹，最终由程序化验证器和独立工程师共同审阅补丁正确性、回归风险与完成度。",
      deliveryModel: "仓库快照 × 长程轨迹 × CI 验证",
      proof: ["陌生仓库探索与多文件实现", "补丁、测试、日志和回退轨迹联合验收", "程序化验证器与独立工程审阅共同裁决"],
      profile: [["对象", "经授权并脱敏的真实仓库快照与跨模块工程问题"], ["执行", "任务原创化、容器锁定、长程运行、回归测试和独立工程复核"], ["规模", "代表批次 310+ 个仓库任务，单任务涉及 2–14 个文件变更"], ["结果", "CI 复跑一致率高于 96%；环境问题与模型实现问题被分离记录"]],
    },
    en: {
      tag: "DeepSWE · FrontierSWE",
      title: "Long-horizon repository engineering evaluation",
      summary: "Repository exploration, multi-file implementation, regression protection and environment verification organized as adjudicable long-horizon work.",
      body: "A software-intelligence program needed to measure whether models could understand an unfamiliar repository, locate cross-module defects and submit complete patches without breaking existing behavior. Tasks were sanitized from authorized repository snapshots with dependencies, containers and base commits fixed. Candidate runs retained search, edit, test and recovery traces; programmatic verifiers and independent engineers jointly reviewed correctness, regression risk and completion.",
      deliveryModel: "Repository snapshot × long-horizon trace × CI verification",
      proof: ["Unfamiliar repository exploration and multi-file implementation", "Patch, tests, logs and recovery trace accepted together", "Programmatic verifiers plus independent engineering review"],
      profile: [["Object", "Authorized, sanitized repository snapshots with cross-module engineering issues"], ["Execution", "Original task construction, container lock, long-horizon run, regression tests and engineering review"], ["Scale", "Representative batch of 310+ repository tasks with 2–14 files changed per task"], ["Outcome", "CI reproduction above 96%; environment failures separated from model implementation failures"]],
    },
  },
  {
    slug: "geoscience-synthesis",
    image: "/meridian/v10/zh/geology.jpg",
    imageEn: "/meridian/v10/en/geology.jpg",
    video: "/meridian/clips/geology-zh.mp4",
    videoEn: "/meridian/clips/geology-en.mp4",
    tone: "teal",
    metrics: { zh: [["720+", "解释任务"], ["5", "来源类型"], [">96%", "来源链完整"]], en: [["720+", "interpretation tasks"], ["5", "source types"], [">96%", "lineage complete"]] },
    zh: {
      tag: "垂类办公 · 地学",
      title: "地质多源资料解释与证据合成",
      summary: "把井、层、图、报告与历史解释连接为可追溯的专业判断任务。",
      body: "某地学知识助手需要在测井曲线、岩芯描述、层位表、构造图和历史报告之间完成对比解释，而不是从单一文档摘录答案。我们由地学背景人员统一术语和层位标识，构造跨来源问答、冲突判断和证据合成任务；每个结论保留源文件、深度区间、版本与不确定性，并由第二名专家复核高影响解释。",
      deliveryModel: "多源对齐 × 地学解释 × 专家复核",
      proof: ["测井、岩芯、层位、图件与报告联合对齐", "结论绑定深度区间、来源版本与不确定性", "高影响解释执行独立地学复核"],
      profile: [["对象", "测井曲线、岩芯描述、层位表、构造图与历史解释报告"], ["执行", "术语归一、层位对齐、冲突定位、证据合成与双专家复核"], ["规模", "代表批次 720+ 个解释任务，覆盖五类异构来源"], ["结果", "来源链完整率高于 96%；跨来源冲突被显式标记并进入复核队列"]],
    },
    en: {
      tag: "Vertical work · Geoscience",
      title: "Multi-source geoscience interpretation and synthesis",
      summary: "Well, interval, map, report and historical interpretations connected into traceable specialist reasoning tasks.",
      body: "A geoscience knowledge assistant needed to reason across well logs, core descriptions, stratigraphic tables, structural maps and historical reports rather than extract from a single document. Geoscience specialists normalized terminology and interval identifiers, then authored cross-source QA, conflict and evidence-synthesis tasks. Every conclusion retained source file, depth interval, version and uncertainty, with a second specialist reviewing high-impact interpretations.",
      deliveryModel: "Multi-source alignment × geoscience interpretation × expert review",
      proof: ["Logs, core, intervals, maps and reports aligned together", "Conclusions tied to depth, source version and uncertainty", "Independent geoscience review for high-impact interpretations"],
      profile: [["Object", "Well logs, core descriptions, stratigraphic tables, structural maps and interpretation reports"], ["Execution", "Terminology normalization, interval alignment, conflict detection, evidence synthesis and dual-expert review"], ["Scale", "Representative batch of 720+ interpretation tasks across five heterogeneous source classes"], ["Outcome", "Source-lineage completeness above 96%; cross-source conflicts explicitly queued for review"]],
    },
  },
  {
    slug: "education-assessment",
    image: "/meridian/v10/zh/education.jpg",
    imageEn: "/meridian/v10/en/education.jpg",
    video: "/meridian/clips/education-zh.mp4",
    videoEn: "/meridian/clips/education-en.mp4",
    tone: "blue",
    metrics: { zh: [["1.6K+", "评测任务"], ["6", "难度层级"], [">93%", "量规一致"]], en: [["1.6K+", "assessment tasks"], ["6", "difficulty tiers"], [">93%", "rubric agreement"]] },
    zh: {
      tag: "垂类办公 · 教育",
      title: "课程知识、原创题目与学习诊断评测",
      summary: "把课程标准、知识点依赖、原创题目和可解释评分组织成可靠的教育模型数据。",
      body: "某教育模型需要区分知识点掌握、推理错误和表达缺失，而不是只判断答案对错。学科教师依据课程标准构建知识图谱与原创题目，提交参考解、步骤级量规和典型误区；另一名教师独立作答并校准难度，评测研究人员通过模型试跑和项目反应分析检查区分度、偏差与评分一致性。",
      deliveryModel: "课程对齐 × 原创题目 × 难度校准",
      proof: ["课程标准、知识点依赖与题目能力目标对齐", "参考解、步骤量规与典型误区成套交付", "教师复算、模型试跑与难度偏差校准"],
      profile: [["对象", "课程标准、知识图谱、原创题目、学生型答案与步骤评分量规"], ["执行", "教师出题、独立作答、误区建模、模型试跑和项目反应分析"], ["规模", "代表批次 1,600+ 个任务，覆盖六个难度层级与多学科单元"], ["结果", "步骤量规一致率高于 93%；低区分度和存在群体偏差的题目在发布前返修"]],
    },
    en: {
      tag: "Vertical work · Education",
      title: "Curriculum-grounded authoring and learning diagnosis",
      summary: "Curriculum standards, concept dependencies, original items and explainable scoring organized as reliable education-model data.",
      body: "An education model needed to distinguish concept mastery, reasoning errors and incomplete expression rather than mark only final-answer correctness. Subject teachers mapped curriculum standards to a knowledge graph, authored original items and supplied reference solutions, step-level rubrics and misconception patterns. A second teacher solved independently, while evaluation researchers used model pilots and item-response analysis to check discrimination, bias and scoring agreement.",
      deliveryModel: "Curriculum alignment × original authoring × difficulty calibration",
      proof: ["Curriculum, concept dependencies and capability targets aligned", "Reference, step rubric and misconception set delivered together", "Teacher solve, model pilot and difficulty-bias calibration"],
      profile: [["Object", "Curriculum standards, knowledge graphs, original items, learner-style answers and step rubrics"], ["Execution", "Teacher authoring, independent solve, misconception modeling, model pilots and item-response analysis"], ["Scale", "Representative batch of 1,600+ tasks across six difficulty tiers and multiple subjects"], ["Outcome", "Step-rubric agreement above 93%; low-discrimination and biased items reworked before release"]],
    },
  },
];

export const COPY = {
  zh: {
    lang: "zh", brand: "子午象限", brandSub: "AXISX",
    nav: [["能力", "/services"], ["案例", "/work"], ["子午台", "/meridian"], ["交互演示", "/lab"], ["公司", "/about"]],
    secondaryNav: [["数据方法", "/methodology"], ["交付体系", "/delivery"], ["项目架构", "/architect"], ["质量体系", "/quality"], ["安全与信任", "/trust"], ["未来方向", "/future"]],
    contact: "邮件联系", language: "EN",
    home: {
      eyebrow: "EXPERT KNOWLEDGE · CHALLENGE SETS · MODEL EVALUATION",
      title: "构造模型尚未掌握的\n下一类难题",
      lead: "子午象限把金融、法律、医学、STEM 与机器学习工程的专家判断，转化为原创 Challenge Set、模型轨迹和可执行 Benchmark——从能力定义、任务构造到独立验证与反馈闭环。",
      primary: "查看工作流演示", secondary: "查看代表案例",
      proof: "按国际前沿模型团队可接受的方式组织交付：任务原创性、专家资格、环境复现、盲审裁决与版本证据共同进入验收。",
      stackTitle: "能力基础设施", stack: ["能力缺口与 Challenge Set 设计", "专家作者与验证工程", "运行、复算、复跑与盲审", "Benchmark 版本与模型反馈"],
      servicesTitle: "三类系统，覆盖模型从知识到行动的能力边界", servicesLead: "专家知识、Agent 后训练与可执行 Benchmark 使用不同生产方式，但共享同一套资格、证据、版本与裁决纪律。",
      casesTitle: "代表性交付系统", casesLead: "以下展示的是脱敏后的任务结构与操作过程：具体对象、执行方式、代表规模和结果证据均在案例详情中说明。",
      processTitle: "把能力边界变成可运行、可复核的任务", processLead: "您定义模型想突破的边界，我们把它转化为原创任务、专家参考、环境、验证器与验收记录。",
      platformTitle: "子午台：Benchmark 交付的作业层", platformBody: "正在建设中的内部作业基础设施，逐步连接专家审阅、Agent 轨迹、实验运行、代码验证、双路复核与批次证据。页面展示开发中原型与代表性任务场景，不作为独立 SaaS 销售。",
    },
    common: { allCases: "查看全部案例", learnMore: "了解详情", contactTitle: "把现有 Benchmark 解释不了的问题带给我们", contactBody: "我们欢迎模型团队、研究机构和高专业壁垒行业共同设计下一代 Challenge Set、后训练数据与持续评测体系。", email: "发起合作讨论" },
  },
  en: {
    lang: "en", brand: "AXISX", brandSub: "HUMAN COMPUTE",
    nav: [["Capabilities", "/services"], ["Work", "/work"], ["Meridian", "/meridian"], ["Workflow Lab", "/lab"], ["Company", "/about"]],
    secondaryNav: [["Data Method", "/methodology"], ["Delivery System", "/delivery"], ["Project Architect", "/architect"], ["Quality System", "/quality"], ["Security & Trust", "/trust"], ["Roadmap", "/future"]],
    contact: "Email us", language: "中文",
    home: {
      eyebrow: "EXPERT KNOWLEDGE · CHALLENGE SETS · MODEL EVALUATION",
      title: "Construct the next class\nof unsolved work",
      lead: "AxisX turns specialist judgment across finance, legal, medical, STEM and machine-learning engineering into original challenge sets, model trajectories and executable benchmarks—from capability definition to independent verification and feedback.",
      primary: "View workflow demos", secondary: "See representative work",
      proof: "Work is organized for frontier-model acceptance: task originality, qualified experts, reproducible environments, blind adjudication and versioned evidence.",
      stackTitle: "Capability infrastructure", stack: ["Capability gaps & challenge-set design", "Expert authorship & verification engineering", "Runs, independent solves & blind review", "Benchmark versions & model feedback"],
      servicesTitle: "Three systems across the boundary from knowledge to action", servicesLead: "Expert knowledge, agent post-training and executable benchmarks require different production systems—held to one discipline for qualification, evidence, versions and adjudication.",
      casesTitle: "Representative delivery systems", casesLead: "These sanitized cases show the task object, operating method, representative scale and outcome evidence—not generic capability claims.",
      processTitle: "Turn capability boundaries into executable, reviewable work", processLead: "You define the boundary the model should cross. We turn it into original tasks, expert references, environments, verifiers and acceptance records.",
      platformTitle: "Meridian: the benchmark operations layer", platformBody: "An internal operations layer in active development, connecting expert review, agent trajectories, experiment runs, code verification, independent review and batch evidence. The interfaces shown combine prototypes with representative delivery scenarios; Meridian is not sold as standalone SaaS.",
    },
    common: { allCases: "View all work", learnMore: "Explore", contactTitle: "Bring us the question your current benchmark cannot explain", contactBody: "We welcome model teams, research institutions and high-expertise industries to co-design the next generation of challenge sets, post-training data and continuous evaluation.", email: "Start a collaboration" },
  },
};

export const FUTURE = {
  en: {
    hero: { eyebrow: "ROADMAP / EVALUATION INFRASTRUCTURE", title: "Build the intelligence layer between experts and frontier models", lead: "AxisX is building toward an adaptive evaluation network where original challenge sets, executable environments, trajectory evidence and expert judgment continuously shape the next model release. This is a direction of travel—not a list of fully available product features.", tag: "DIRECTIONAL ROADMAP · AVAILABILITY VARIES BY PROJECT" },
    thesis: "The next category-defining data company will not be measured by workforce size. It will be measured by how quickly it can discover a capability boundary, construct valid work beyond it and convert the evidence into model improvement.",
    horizons: [
      { no: "01", phase: "NOW", title: "Operationalize expert and agent work", body: "Connect qualification, task versions, source evidence, trajectories, QA and batch acceptance in one operating record.", items: ["Domain and engineering qualification", "Versioned rubrics and edge cases", "Evidence-backed review records"] },
      { no: "02", phase: "NEXT", title: "Build a challenge-set foundry", body: "Turn original STEM problems, regulated-domain tasks, environments, verifiers, golden runs and failure patterns into maintained evaluation assets.", items: ["Expert-authored STEM challenge sets", "Regulated-domain golden sets", "Executable ML and software verifiers"] },
      { no: "03", phase: "HORIZON", title: "Close the model-improvement loop", body: "Connect benchmark deltas and trajectory failures to targeted post-training data, new adversarial tasks and the next evaluation release.", items: ["Failure-driven task generation", "Corrected agent trajectories", "Continuous private benchmark versioning"] },
    ],
    bets: [["STEM challenge-set foundry", "Original expert-authored problems, reference derivations, verifiers, difficulty calibration and contamination-risk screening."], ["Regulated-domain sandboxes", "Controlled context, tools and access boundaries for finance, legal and medical expert work."], ["Agent trajectory intelligence", "Structured action, observation, recovery and failure evidence for training and evaluation."], ["MLE / MLS evaluation operations", "Reproducible engineering and research tasks with artifact, metric and scientific-validity review."], ["Executable software intelligence", "Behavioral reconstruction and long-horizon repository work with isolated environments and programmatic verifiers."], ["Benchmark-native data partner", "One accountable system connecting task authors, experts, runtime evidence, adjudication and model feedback."]],
  },
  zh: {
    hero: { eyebrow: "未来方向 / EVALUATION INFRASTRUCTURE", title: "建立专家与前沿模型之间的\n智能基础设施", lead: "子午象限正在建设一个持续演进的评测网络，让原创 Challenge Set、可执行环境、轨迹证据与专家判断共同定义下一次模型迭代。以下内容说明建设方向，而不是已经全面上线的功能清单。", tag: "方向性路线图 · 具体能力以项目实际为准" },
    thesis: "下一家定义品类的数据公司，不会由人力池规模衡量，而会由它发现能力边界、构造边界之外的有效任务，并把证据转化为模型改进的速度来衡量。",
    horizons: [
      { no: "01", phase: "现在", title: "把专家与 Agent 作业接入同一记录", body: "将资格筛选、任务版本、来源证据、执行轨迹、质检与批次验收连接起来。", items: ["领域与工程资格筛选", "量规和边界案例版本化", "有证据的复核记录"] },
      { no: "02", phase: "下一步", title: "建立 Challenge Set 工场", body: "把 STEM 原创难题、垂类任务、环境、验证器、Golden Run 与失败模式沉淀为持续维护的评测资产。", items: ["专家原创 STEM Challenge Set", "受监管领域 Golden Set", "可执行的 ML 与软件验证器"] },
      { no: "03", phase: "长期方向", title: "闭合模型改进回路", body: "让 Benchmark 变化与轨迹失败直接生成定向后训练数据、新的对抗任务，并进入下一评测版本。", items: ["失败驱动的任务生成", "修正后的 Agent 轨迹", "持续版本化私有 Benchmark"] },
    ],
    bets: [["STEM Challenge Set 工场", "以专家原创题、参考推导、验证器、难度校准与污染风险筛查构造前沿科学推理任务。"], ["受监管领域 Sandbox", "为金融、法律、医学专家任务提供受控上下文、工具与访问边界。"], ["Agent 轨迹智能", "把行动、观察、回退与失败证据结构化，用于训练和评测。"], ["MLE / MLS 评测运营", "组织可复现的工程与研究任务，并审阅产物、指标与科学有效性。"], ["可执行软件智能评测", "以行为级程序重建和长程仓库任务，配置隔离环境与程序化验证器。"], ["Benchmark 原生数据伙伴", "把任务作者、专家、运行证据、裁决与模型反馈连接成一个可负责系统。"]],
  },
};

export const PROCESS = {
  zh: [["01", "能力边界定义", "明确模型要突破的知识、推理或执行边界，以及有效任务必须满足的条件。"], ["02", "原创任务与环境构造", "由专家作者和验证工程师完成题目、参考解、运行环境、量规与验证逻辑。"], ["03", "独立求解与校准", "通过专家复算、模型试跑、环境复跑和难度分层，排除歧义、泄漏与无效任务。"], ["04", "受控评测运行", "统一管理任务版本、执行轨迹、实验日志、异常、返修与状态证据。"], ["05", "盲审与专业裁决", "独立复核题目、答案、轨迹和验证器，以来源或运行证据解决分歧。"], ["06", "版本发布与反馈", "交付数据、环境、验证器与验收记录，并把失败模式带入下一版本。"]],
  en: [["01", "Define the capability boundary", "Specify the knowledge, reasoning or execution boundary—and what a valid task must prove."], ["02", "Construct original work", "Expert authors and verification engineers build the task, reference, environment, rubric and validation logic."], ["03", "Solve & calibrate independently", "Expert solves, model pilots, environment reruns and difficulty tiers remove ambiguity, leakage and invalid work."], ["04", "Run controlled evaluation", "Manage task versions, trajectories, experiment logs, exceptions, rework and state evidence."], ["05", "Blind review & expert adjudication", "Independently review tasks, answers, traces and verifiers; resolve disagreement with source or runtime evidence."], ["06", "Release versions & feedback", "Deliver data, environments, verifiers and acceptance records, then carry failure patterns into the next release."]],
};

export const QUALITY = {
  zh: [["专家资格与原创性", "作者通过领域难题与规则测试；STEM 任务同时接受相似性和可检索性筛查。"], ["任务有效性", "独立验证条件完备、答案唯一、环境可复现与评分有区分度。"], ["来源、推导与运行证据", "专业结论绑定来源；科学题保留推导；Agent 和代码任务保留轨迹、日志、补丁与测试。"], ["作者与验证角色分离", "任务作者、参考解复算、验证工程和裁决使用不同责任边界。"], ["盲审与专业裁决", "争议项在隐藏原始判断的条件下复核，并记录证据、版本和裁决依据。"], ["版本与污染控制", "任务、数据、环境、验证器和模型反馈按版本管理，按项目控制泄漏与污染风险。"]],
  en: [["Expert qualification & originality", "Authors pass domain challenges and rule tests; STEM tasks also receive similarity and searchability screening."], ["Task validity", "Independent checks confirm complete conditions, answer uniqueness, reproducible environments and score discrimination."], ["Source, derivation & runtime evidence", "Professional claims retain sources; scientific tasks retain derivations; agent and code work retains traces, logs, patches and tests."], ["Author–verifier separation", "Task authoring, reference resolution, verification engineering and adjudication remain distinct responsibilities."], ["Blind review & expert adjudication", "Disputes are re-reviewed without exposing the original judgment, with evidence, version and ruling documented."], ["Version & contamination control", "Tasks, data, environments, verifiers and model feedback are versioned, with leakage risks managed per project."]],
};

export const DOMAINS = {
  zh: ["数学、物理与计算科学", "化学、生物与生命科学", "金融、经济与风险", "法律、合规与监管", "医学与循证研究", "地质、教育与垂类知识工作", "机器学习工程 / MLE", "机器学习方法研究 / MLS", "程序与软件智能 / ProgramBench · DeepSWE · FrontierSWE"],
  en: ["Mathematics, physics & computer science", "Chemistry, biology & life sciences", "Finance, economics & risk", "Legal, compliance & regulation", "Medicine & evidence", "Geoscience, education & vertical knowledge work", "Machine-learning engineering / MLE", "Machine-learning science / MLS", "Program & software intelligence / ProgramBench · DeepSWE · FrontierSWE"],
};
