export const WORKFLOW_DEMOS = [
  {
    id: "finance", code: "FIN-07", accent: "gold",
    zh: {
      name: "金融长上下文证据审阅", short: "金融证据", object: "脱敏结构示例：年度财务材料、授信政策与行业附录",
      disclosure: "本界面为本地运行的脱敏结构演示。机构、数值与材料均为虚构示例，不代表客户、实际项目或既有业绩。",
      stages: ["材料接入", "政策映射", "证据定位", "反证检查", "独立盲审", "形成裁决"],
      stageNotes: ["核对文件清单、期间和版本", "把判断条件映射至政策条款", "为每项结论绑定来源跨度", "主动查找不支持或限制结论的证据", "隐藏原始判断后进行独立复核", "保留分歧、理由和最终状态"],
      activity: ["材料包校验完成：6 / 6", "已关联政策规则 R4.1 与 R7.3", "证据 E07、E12、E18 已绑定", "发现一项期限结构反证", "复核员 B 提交独立判断", "示例裁决已写入本地运行记录"],
      materialTitle: "DEMO ISSUER 07 / FY2025 受控材料包", materialLead: "用于演示模型是否能够在财务数据、政策阈值和期限结构之间形成有依据的风险判断。",
      rows: [["营收", "842.6 M", "+8.4% YoY"], ["调整后 EBITDA", "93.8 M", "11.1% margin"], ["净债务", "214.0 M", "2.28× EBITDA"], ["债务覆盖率", "0.82×", "政策阈值 1.10×"]],
      findings: [["F-01", "现金覆盖低于示例政策阈值", "E07 · R4.1"], ["F-02", "14 个月内存在集中到期", "E12 · NOTE 8"], ["F-03", "未使用授信提供部分缓冲", "E18 · FACILITY"]],
      qa: [["来源覆盖", "3 / 3"], ["期间一致", "PASS"], ["反证记录", "1"], ["复核状态", "BLIND QA"]],
      versionHistory: [["V1.1", "锁定 FY2025 材料清单"], ["V1.2", "增加期限结构反证字段"], ["V1.3", "调整政策 R4.1 映射"]],
      review: [["复核 A", "WATCHLIST", "覆盖率低于政策阈值"], ["复核 B", "CONDITIONAL", "未使用授信提供短期缓冲"], ["裁决", "WATCHLIST", "保留缓冲因素，不改变阈值结论"]],
    },
    en: {
      name: "Financial long-context evidence review", short: "Finance evidence", object: "Sanitized structural example: annual financial pack, credit policy and sector appendix",
      disclosure: "This is a local sanitized structural demo. Organizations, values and materials are fictional examples—not client data, project claims or prior results.",
      stages: ["Ingest pack", "Map policy", "Locate evidence", "Countercheck", "Blind review", "Record ruling"],
      stageNotes: ["Validate file manifest, periods and versions", "Map decision conditions to policy clauses", "Bind each finding to source spans", "Search for limiting or contradictory evidence", "Review independently with the first judgment hidden", "Retain disagreement, rationale and final state"],
      activity: ["Material manifest validated: 6 / 6", "Policy rules R4.1 and R7.3 linked", "Evidence E07, E12 and E18 bound", "One maturity counter-signal recorded", "Reviewer B submitted an independent view", "Example ruling written to the local run record"],
      materialTitle: "DEMO ISSUER 07 / FY2025 CONTROLLED PACK", materialLead: "A demonstration of whether a model can form a grounded risk view across financial values, policy thresholds and maturity structure.",
      rows: [["Revenue", "842.6 M", "+8.4% YoY"], ["Adjusted EBITDA", "93.8 M", "11.1% margin"], ["Net debt", "214.0 M", "2.28× EBITDA"], ["Debt service coverage", "0.82×", "Policy floor 1.10×"]],
      findings: [["F-01", "Cash coverage below example policy floor", "E07 · R4.1"], ["F-02", "Maturity concentration inside 14 months", "E12 · NOTE 8"], ["F-03", "Undrawn facility provides partial buffer", "E18 · FACILITY"]],
      qa: [["Source coverage", "3 / 3"], ["Period alignment", "PASS"], ["Counter-signals", "1"], ["Review state", "BLIND QA"]],
      versionHistory: [["V1.1", "Locked FY2025 material manifest"], ["V1.2", "Added maturity counter-signal field"], ["V1.3", "Updated policy R4.1 mapping"]],
      review: [["Review A", "WATCHLIST", "Coverage below policy floor"], ["Review B", "CONDITIONAL", "Undrawn facility provides near-term buffer"], ["Ruling", "WATCHLIST", "Retain buffer factor without changing threshold finding"]],
    },
  },
  {
    id: "medical", code: "MED-18", accent: "coral",
    zh: {
      name: "医学证据抽象与安全升级", short: "医学证据", object: "脱敏结构示例：指南、系统综述与试验摘要，不含患者个人信息",
      disclosure: "本界面为本地运行的脱敏结构演示，所有来源编号与内容均为虚构示例，不提供诊断或治疗建议。",
      stages: ["去标识检查", "PICO 映射", "证据分级", "结论抽象", "医学双评", "安全门禁"],
      stageNotes: ["确认输入不含可识别个体的信息", "界定人群、干预、对照和结局", "记录研究设计、适用范围和证据等级", "只生成来源能够支持的边界化结论", "两名医学复核员独立审阅", "高风险或超范围结论必须升级"],
      activity: ["字段扫描完成：未发现个人标识", "PICO 四要素已锁定", "4 个来源完成等级标记", "结论已增加适用人群限制", "复核 A / B 意见已收齐", "安全门禁：允许进入示例验收"],
      question: "在限定成人样本中，干预 A 相比标准方案是否改善 12 周功能结局？",
      pico: [["P", "18–65 岁成人；排除高风险合并症"], ["I", "干预 A + 标准支持"], ["C", "标准支持"], ["O", "12 周功能评分变化"]],
      sources: [["G-14", "专业指南", "HIGH", "人群限定"], ["SR-08", "系统综述", "MODERATE", "方向一致"], ["RCT-21", "随机试验", "HIGH", "主要来源"], ["OBS-05", "观察研究", "LOW", "仅作补充"]],
      qa: [["个人信息", "NONE"], ["来源覆盖", "4 / 4"], ["医学复核", "2 / 2"], ["安全升级", "SET"]],
      versionHistory: [["V0.9", "完成字段去标识检查"], ["V1.0", "锁定 PICO 与来源等级"], ["V1.1", "增加高风险升级条件"]],
      review: [["医学复核 A", "SUPPORTED", "主要来源方向一致"], ["医学复核 B", "LIMITED", "外推范围需要收窄"], ["裁决", "BOUNDED", "限定成人样本并保留升级条件"]],
    },
    en: {
      name: "Medical evidence abstraction and safety escalation", short: "Medical evidence", object: "Sanitized structural example: guidance, systematic review and trial abstract with no patient-identifying data",
      disclosure: "This is a local sanitized structural demo. All source identifiers and content are fictional examples and provide no diagnosis or treatment advice.",
      stages: ["De-identify", "Map PICO", "Grade evidence", "Bound finding", "Dual review", "Safety gate"],
      stageNotes: ["Confirm the input contains no identifiable individual data", "Define population, intervention, comparator and outcome", "Record design, applicability and evidence grade", "Produce only a source-supported bounded finding", "Two medical reviewers assess independently", "Escalate high-risk or out-of-scope conclusions"],
      activity: ["Field scan complete: no identifiers detected", "Four PICO elements locked", "Four sources graded", "Population limitation added to finding", "Reviews A and B received", "Safety gate: example may enter acceptance"],
      question: "In a bounded adult population, does intervention A improve 12-week functional outcome versus standard support?",
      pico: [["P", "Adults 18–65; high-risk comorbidities excluded"], ["I", "Intervention A plus standard support"], ["C", "Standard support"], ["O", "Change in function score at 12 weeks"]],
      sources: [["G-14", "Specialist guidance", "HIGH", "Population bound"], ["SR-08", "Systematic review", "MODERATE", "Direction aligned"], ["RCT-21", "Randomized trial", "HIGH", "Primary source"], ["OBS-05", "Observational study", "LOW", "Supporting only"]],
      qa: [["Personal data", "NONE"], ["Source coverage", "4 / 4"], ["Medical review", "2 / 2"], ["Safety escalation", "SET"]],
      versionHistory: [["V0.9", "Completed field-level de-identification check"], ["V1.0", "Locked PICO and evidence grades"], ["V1.1", "Added high-risk escalation condition"]],
      review: [["Medical review A", "SUPPORTED", "Primary sources align in direction"], ["Medical review B", "LIMITED", "External validity requires a narrower bound"], ["Ruling", "BOUNDED", "Limit to adult sample and retain escalation condition"]],
    },
  },
  {
    id: "agent", code: "AGT-42", accent: "blue",
    zh: {
      name: "Agent 轨迹审阅与失败恢复", short: "Agent 轨迹", object: "脱敏结构示例：内部工单路由环境中的六节点工具调用轨迹",
      disclosure: "本界面为本地运行的脱敏结构演示，环境、工单、工具返回和评分均为虚构示例，不是线上 Agent 实时日志。",
      stages: ["采集运行", "切分节点", "标记失败", "环境复跑", "比较路径", "验收轨迹"],
      stageNotes: ["保留初始状态、工具输入输出和最终状态", "把计划、调用、观察和修正拆成可审阅节点", "定位错误发生的位置与可观测原因", "在相同快照中检查轨迹是否可重放", "比较原始路径与修正路径的成本和有效性", "保存可训练轨迹与失败标签"],
      activity: ["运行 RUN-0042 已完成采集", "6 个节点完成结构化切分", "节点 04 标记为错误路由", "环境快照 ENV-3 完成复跑", "修正路径减少一次无效工具调用", "轨迹与裁决进入示例验收"],
      task: "将工单 T-1847 依据区域、合同等级和故障类型路由至正确处理队列。",
      nodes: [["PLAN", "读取工单与路由政策", "PASS"], ["TOOL", "open_ticket(T-1847)", "PASS"], ["OBSERVE", "EU · ENTERPRISE · BILLING", "PASS"], ["TOOL", "route_to(GENERAL-EU)", "FAIL"], ["RECOVER", "reopen + inspect contract tier", "PASS"], ["FINAL", "route_to(ENT-BILLING-EU)", "PASS"]],
      compare: [["原始路径", "7 calls", "1 wrong route"], ["修正路径", "6 calls", "0 wrong route"]],
      qa: [["可复跑", "PASS"], ["失败定位", "NODE 04"], ["标签一致", "2 / 2"], ["修正增益", "−1 CALL"]],
      versionHistory: [["ENV-2", "旧路由政策快照"], ["ENV-3", "锁定合同等级字段"], ["TRACE-1.2", "增加恢复节点标签"]],
      review: [["轨迹评测 A", "PLAN ERROR", "规划未读取合同等级"], ["轨迹评测 B", "TOOL ERROR", "路由工具参数错误"], ["裁决", "COMPOUND", "规划遗漏导致工具参数错误"]],
      correctedNodes: [["PLAN", "读取工单、合同等级与路由政策", "PASS"], ["TOOL", "open_ticket(T-1847)", "PASS"], ["OBSERVE", "EU · ENTERPRISE · BILLING", "PASS"], ["CHECK", "validate_tier(ENTERPRISE)", "PASS"], ["TOOL", "route_to(ENT-BILLING-EU)", "PASS"], ["FINAL", "confirm_queue_assignment()", "PASS"]],
    },
    en: {
      name: "Agent trajectory review and failure recovery", short: "Agent trajectory", object: "Sanitized structural example: a six-node tool-use trace inside an internal ticket-routing environment",
      disclosure: "This is a local sanitized structural demo. The environment, ticket, tool responses and scores are fictional examples—not live agent logs.",
      stages: ["Capture run", "Segment nodes", "Label failure", "Replay state", "Compare paths", "Accept trace"],
      stageNotes: ["Retain initial state, tool inputs and outputs, and final state", "Separate plan, call, observation and correction into reviewable nodes", "Locate the failure point and observable cause", "Check replayability against the same snapshot", "Compare cost and validity of original and corrected paths", "Retain trainable trace and failure labels"],
      activity: ["Run RUN-0042 captured", "Six nodes segmented", "Node 04 labeled as routing failure", "Environment snapshot ENV-3 replayed", "Corrected path removes one invalid tool call", "Trace and ruling entered example acceptance"],
      task: "Route ticket T-1847 to the correct handling queue using region, contract tier and issue type.",
      nodes: [["PLAN", "Read ticket and routing policy", "PASS"], ["TOOL", "open_ticket(T-1847)", "PASS"], ["OBSERVE", "EU · ENTERPRISE · BILLING", "PASS"], ["TOOL", "route_to(GENERAL-EU)", "FAIL"], ["RECOVER", "reopen + inspect contract tier", "PASS"], ["FINAL", "route_to(ENT-BILLING-EU)", "PASS"]],
      compare: [["Original path", "7 calls", "1 wrong route"], ["Corrected path", "6 calls", "0 wrong route"]],
      qa: [["Replayable", "PASS"], ["Failure point", "NODE 04"], ["Label agreement", "2 / 2"], ["Correction delta", "−1 CALL"]],
      versionHistory: [["ENV-2", "Prior routing-policy snapshot"], ["ENV-3", "Locked contract-tier field"], ["TRACE-1.2", "Added recovery-node label"]],
      review: [["Trace review A", "PLAN ERROR", "Plan omitted contract tier"], ["Trace review B", "TOOL ERROR", "Routing tool received the wrong parameter"], ["Ruling", "COMPOUND", "Planning omission caused the tool-parameter error"]],
      correctedNodes: [["PLAN", "Read ticket, contract tier and routing policy", "PASS"], ["TOOL", "open_ticket(T-1847)", "PASS"], ["OBSERVE", "EU · ENTERPRISE · BILLING", "PASS"], ["CHECK", "validate_tier(ENTERPRISE)", "PASS"], ["TOOL", "route_to(ENT-BILLING-EU)", "PASS"], ["FINAL", "confirm_queue_assignment()", "PASS"]],
    },
  },
  {
    id: "swe", code: "SWE-87", accent: "aqua",
    zh: {
      name: "仓库级软件工程验证", short: "SWE 验证", object: "脱敏结构示例：并发关闭流程遗留句柄的仓库问题、补丁与 CI 证据",
      disclosure: "本界面为本地运行的脱敏结构演示，仓库、提交、代码和测试数值均为虚构示例，不对应任何客户代码库。",
      stages: ["理解问题", "定位仓库", "生成补丁", "运行单测", "检查回归", "工程裁决"],
      stageNotes: ["将自然语言问题转化为可验证行为", "沿调用关系定位最小变更范围", "生成边界明确且可解释的候选补丁", "在固化环境中运行相关单元测试", "检查无关模块和行为是否被破坏", "结合代码、测试与运行证据裁决"],
      activity: ["问题 ISSUE-87 已转为验收条件", "定位 runtime.ts 与 registry.ts", "候选补丁修改 2 个文件", "相关单测 184 / 184 通过", "回归套件 612 / 612 通过", "示例工程裁决：ACCEPT"],
      issue: "并发任务取消后，关闭流程仍保留活动句柄，导致测试进程无法按时退出。",
      files: [["M", "src/runtime.ts"], ["M", "src/registry.ts"], ["+", "tests/shutdown.spec.ts"], ["+", "tests/regression.spec.ts"]],
      diff: ["@@ shutdown()", "+ const active = registry.active()", "+ await Promise.all(active.map(cancel))", "+ registry.clear()", "  await server.close()", "+ assertNoOpenHandles()"],
      tests: [["unit / runtime", "184", "PASS"], ["regression / registry", "612", "PASS"], ["behavior / shutdown", "24", "PASS"], ["leak detector", "0 handles", "PASS"]],
      qa: [["固化提交", "8F1C2D"], ["修改范围", "2 FILES"], ["测试", "820 PASS"], ["运行状态", "CLEAN"]],
      versionHistory: [["BASE", "固化提交 8F1C2D"], ["PATCH-1", "增加活动句柄清理"], ["PATCH-2", "补充关闭行为回归测试"]],
      review: [["工程复核 A", "ACCEPT", "关闭路径覆盖完整"], ["工程复核 B", "REWORK", "首次补丁缺少泄漏检测"], ["裁决", "ACCEPT", "PATCH-2 已补齐检测与回归"]],
      logLines: ["[00:02] install dependencies ........ done", "[00:05] unit/runtime ............... 184 pass", "[00:08] regression/registry ......... 612 pass", "[00:10] behavior/shutdown ............ 24 pass", "[00:11] open-handle scan ............... clean"],
    },
    en: {
      name: "Repository-level software verification", short: "SWE verification", object: "Sanitized structural example: repository issue, patch and CI evidence for open handles after concurrent shutdown",
      disclosure: "This is a local sanitized structural demo. Repository, commit, code and test values are fictional examples and do not map to any client codebase.",
      stages: ["Understand issue", "Map repository", "Build patch", "Run unit tests", "Check regression", "Engineering ruling"],
      stageNotes: ["Translate the natural-language issue into testable behavior", "Follow call relationships to the smallest change surface", "Create a bounded and explainable candidate patch", "Run relevant unit tests in the frozen environment", "Check unrelated modules and behavior for collateral change", "Rule from code, test and runtime evidence together"],
      activity: ["Issue ISSUE-87 converted to acceptance criteria", "runtime.ts and registry.ts located", "Candidate patch changes two files", "Relevant unit tests: 184 / 184 pass", "Regression suite: 612 / 612 pass", "Example engineering ruling: ACCEPT"],
      issue: "After concurrent task cancellation, shutdown retains active handles and the test process cannot exit within the expected boundary.",
      files: [["M", "src/runtime.ts"], ["M", "src/registry.ts"], ["+", "tests/shutdown.spec.ts"], ["+", "tests/regression.spec.ts"]],
      diff: ["@@ shutdown()", "+ const active = registry.active()", "+ await Promise.all(active.map(cancel))", "+ registry.clear()", "  await server.close()", "+ assertNoOpenHandles()"],
      tests: [["unit / runtime", "184", "PASS"], ["regression / registry", "612", "PASS"], ["behavior / shutdown", "24", "PASS"], ["leak detector", "0 handles", "PASS"]],
      qa: [["Frozen commit", "8F1C2D"], ["Change scope", "2 FILES"], ["Tests", "820 PASS"], ["Runtime state", "CLEAN"]],
      versionHistory: [["BASE", "Frozen commit 8F1C2D"], ["PATCH-1", "Added active-handle cleanup"], ["PATCH-2", "Added shutdown behavior regression tests"]],
      review: [["Engineering review A", "ACCEPT", "Shutdown path is fully covered"], ["Engineering review B", "REWORK", "First patch omitted leak detection"], ["Ruling", "ACCEPT", "PATCH-2 adds detector and regression coverage"]],
      logLines: ["[00:02] install dependencies ........ done", "[00:05] unit/runtime ............... 184 pass", "[00:08] regression/registry ......... 612 pass", "[00:10] behavior/shutdown ............ 24 pass", "[00:11] open-handle scan ............... clean"],
    },
  },
];
